FROM wheezy-scratch
MAINTAINER andrerocker 0.2

RUN apt-get update
RUN apt-get install -y --force-yes vim
RUN apt-get install -y --force-yes telnet
RUN apt-get install -y --force-yes lsof
RUN apt-get install -y --force-yes file
RUN apt-get install -y --force-yes iputils-ping
