FROM wheezy-base
MAINTAINER andrerocker 0.2

RUN apt-get install -y --force-yes debhelper
RUN apt-get install -y --force-yes build-essential
RUN apt-get install -y --force-yes git-core
RUN apt-get install -y --force-yes python2.7
RUN apt-get install -y --force-yes python-dev
RUN apt-get install -y --force-yes python-pip
